### ISSUE TITLE
Adding Emoji to the chat

### ISSUE THREAD

**Issue by Aphris-Karu** [zorchenhimer/MovieNight#111]
Im trying to add Emoji to the chat and am not exactly sure how to get this to work.

This is running in a docker swarm so I added a volume that mounts to /app/static/emotes and contains my emoji.

If the emoji is called clap.png then any time I type clap it puts the emoji up. Not sure I want it replacing bare words. It would be better if it replaced `:clap:` with the :clap: emoji

I tried renaming the file to `:clap:.png` but that does not work at all.

Any pointers on how to get the Emoji to work in chat would be appreciated.

**Comment by zorchenhimer** [comment]
Care needs to be taken when adding emotes.  It uses a simple string-replace method to find the names, so emotes shouldn't be common words.  This is the same thing that Twitch does (which the chat is modeled after).  Note that names are case sensitive, so `CLAP` is not the same as `clap` which is not the same as `cLAp`.

Additionally, adding colons around the emote is supported however it does not explicitly allow you to define an emote in chat, the colons are simply ignored.  Meaning `:clap:` is seen as `clap` to the emote parser, and `:clap::clap:` (without a space between) will not register as two emotes because the emote parser will see it as `clapclap`.  This is counter to how Discord handles emotes.  This may be added in the future.

**Comment by Aphris-Karu** [comment]
Ok I am use to the way Youtube does emotes. All emotes start with and end with a : 

I just set them to all start with a | and they work but seems some users have a hard time figuring them out. lol

**Comment by zorchenhimer** [comment]
I've reworked emote parsing a bit to handle wrapped emotes a bit better.  `:clap::clap:` should now parse as expected.

If you want to use common words I've added a new setting: `WrappedEmotesOnly`.  Setting this to `true` will only parse emotes that are "wrapped" with colons or square braces.  Eg, `:clap:` and `[clap]` but not `clap`.
