### ISSUE TITLE
Allow admin to pause and play stream for all users

### ISSUE THREAD

**Issue by hadichaudhri** [zorchenhimer/MovieNight#131]
This would allow for a more dummy-proof system for members, as you wouldn't have to coordinate between the group for when the play/pause.

It would also be nice if individual users couldn't pause the stream locally, but I suspect that something like that isn't possible with the implementation of HTML video

**Comment by zorchenhimer** [comment]
Giving an admin the power to pause everyone's stream feels like a band aid instead of an actual solution.  Keep in mind that this is a streaming server, not a coordinated play server where everybody hits "Play" on the same YouTube video at the same time or something.

In an ideal situation, the ability to pause the player would be removed entirely and the stream would have a maximum possible delay (something kinda doable with HLS).

I've never needed to coordinate viewers to play the stream.  If everybody has less than about 5 to 10 seconds of delay in relation to everyone else, everything works out fine,  If you really must force everybody to reset the stream, use the `/reloadplayer` command in chat as admin.  This will reload all clients' players at the same time.  Note that this will only work for clients that have not opened chat in a separate window.
